from app.post_builder import VK_MESSAGE_LIMIT, build_post_text, clean_description

_YT_AUTOGEN = """Provided to YouTube by Союз Мьюзик / Soldout Music

Танцуй · Lover

Танцуй

℗ 2026 Союз Мьюзик / Soldout Music

Released on: 2023-07-14

Auto-generated by YouTube."""


def test_clean_description_drops_youtube_autogenerated():
    assert clean_description(_YT_AUTOGEN) == ""


def test_clean_description_keeps_normal_text():
    assert clean_description("Просто описание трека") == "Просто описание трека"


def test_post_without_autogenerated_has_only_title_and_ad():
    text = build_post_text("Танцуй", clean_description(_YT_AUTOGEN), "Реклама")
    assert "Provided to YouTube" not in text
    assert "Auto-generated" not in text
    assert text == "Танцуй\n\nРеклама"


def test_builds_title_description_ad_in_order():
    text = build_post_text("Заголовок", "Описание", "Реклама")
    assert text == "Заголовок\n\nОписание\n\nРеклама"


def test_skips_empty_parts():
    text = build_post_text("Заголовок", "", "Реклама")
    assert text == "Заголовок\n\nРеклама"


def test_trims_when_over_limit_but_keeps_title_and_ad():
    long_description = "x" * (VK_MESSAGE_LIMIT + 500)
    text = build_post_text("Название", long_description, "Реклама")

    assert len(text) <= VK_MESSAGE_LIMIT
    assert text.startswith("Название")
    assert text.endswith("Реклама")
