from __future__ import annotations

import re

from app import seo

# VK ограничивает текст записи на стене ~16000 символами.
VK_MESSAGE_LIMIT = 16000

# В теге VK допустимы только буквы/цифры/подчёркивание — на первом же пробеле
# или дефисе тег обрывается, поэтому чистим заранее.
_HASHTAG_JUNK = re.compile(r"[^\w]", re.UNICODE)
_UNDERSCORE_RUN = re.compile(r"_{2,}")

# Маркеры авто-сгенерированного описания YouTube Music (Art Tracks / Topic).
# У таких роликов ВСЁ описание — служебный боилерплейт («Provided to YouTube
# by…», «Auto-generated by YouTube»), полезного текста нет — выбрасываем целиком.
_YT_AUTOGEN_MARKERS = ("Provided to YouTube by", "Auto-generated by YouTube")


def build_hashtag(template: str, artist: str, name: str, group: str) -> str:
    """Тег в формате VK «#релиз@группа» — привязка записи к сообществу.

    Шаблон решает, насколько тег уникален: «{artist}_{name}» даёт свой тег
    каждому треку, «{artist}» — общий на всего исполнителя. VK принимает в теге
    буквы (в т.ч. кириллицу), цифры и подчёркивание; остальное выбрасываем,
    иначе тег обрывается на первом же пробеле или дефисе.
    """
    raw = template.format(artist=artist, name=name).lower()
    # «ARGUMENTS & FACTS»: «&» выбрасывается и оставляет двойное подчёркивание —
    # схлопываем, иначе тег выглядит как опечатка.
    slug = _UNDERSCORE_RUN.sub("_", _HASHTAG_JUNK.sub("", raw.replace(" ", "_"))).strip("_")
    if not slug:
        return ""
    return f"#{slug}@{group}" if group else f"#{slug}"


def build_release_header(style, artist: str, name: str, kind: str) -> str:
    """Первая строка поста: «🎧 Artist — Name (Album) | Без цензуры».

    Она же идёт названием видео — чтобы карточка в каталоге VK и запись на стене
    назывались одинаково.
    """
    line = _release_line(artist, name, kind, style.title_suffix)
    return " ".join(part for part in (style.flag, line) if part)


def build_release_text(style, artist: str, name: str, kind: str, body: str = "") -> str:
    """Пост-релиз: шапка, необязательный треклист, ссылки, теги.

    style — PostStyle из config. Пустой url просто не даёт своей строки, поэтому
    ссылку на канал можно убрать, не трогая код.
    """
    links = [
        f"{label} {url}".strip()
        for label, url in (
            (style.listen_label, style.listen_url),
            (style.channel_label, style.channel_url),
        )
        if url
    ]
    tags = _release_tags(style, artist, name, style.post_tag_limit)

    blocks = [build_release_header(style, artist, name, kind)]
    if body.strip():
        blocks.append(body.strip())
    blocks.append("\n".join(links + ([" ".join(tags)] if tags else [])))
    return "\n\n".join(block for block in blocks if block)


def seo_configured(style) -> bool:
    """Заполнены ли SEO-поля стиля.

    Пока они пусты, публикации обязаны выглядеть ТОЧНО как раньше: один тег по
    hashtag_template, описание видео = текст записи. Без этой развилки включение SEO
    было бы необратимым и незаметно меняло оформление у всех, кто его не настраивал."""
    return bool(
        getattr(style, "search_phrases", None)
        or getattr(style, "base_tags", None)
        or getattr(style, "service_block", "")
    )


def build_release_video_description(
    style, artist: str, name: str, kind: str, body: str = ""
) -> str:
    """Описание ВИДЕОЗАПИСИ релиза — большое, поисковое (ТЗ 2026-08-10).

    Отдельно от текста записи: у видеообъекта VK своё индексируемое поле, в ленте оно
    свёрнуто, поэтому туда уходят варианты запроса, блок про сервис и полный набор
    тегов. Без настроенных SEO-полей возвращает ровно текст записи — прежнее
    поведение, при котором описание видео и запись совпадали."""
    if not seo_configured(style):
        return build_release_text(style, artist, name, kind, body)

    links = "\n".join(
        f"{label} {url}".strip()
        for label, url in (
            (style.listen_label, style.listen_url),
            (style.channel_label, style.channel_url),
        )
        if url
    )
    return seo.build_video_description(
        header=build_release_header(style, artist, name, kind),
        body="\n\n".join(part for part in (body.strip(), links) if part),
        subjects=_release_subjects(artist, name),
        phrases=style.search_phrases,
        base_tags=style.base_tags,
        group=style.hashtag_group,
        tag_limit=style.video_tag_limit,
        service_block=style.service_block,
    )


def _release_subjects(artist: str, name: str) -> list[str]:
    """Что человек реально набирает в поиске: артист, название и связка «артист название»."""
    subjects = [part for part in (artist.strip(), name.strip()) if part]
    if len(subjects) == 2:
        subjects.append(f"{subjects[0]} {subjects[1]}")
    return subjects


def _release_tags(style, artist: str, name: str, limit: int) -> list[str]:
    """Теги релиза. Ключевой тег по hashtag_template идёт ПЕРВЫМ — он уникален для
    релиза и именно он склеивает трек с его альбомом. Дальше — теги по артисту и
    названию плюс постоянные теги сообщества, но только если SEO настроено."""
    primary = build_hashtag(style.hashtag_template, artist, name, style.hashtag_group)
    tags = [primary] if primary else []
    if not seo_configured(style):
        return tags
    for tag in seo.build_hashtags(
        _release_subjects(artist, name), style.base_tags, style.hashtag_group, limit
    ):
        if tag not in tags:
            tags.append(tag)
    return tags[:limit] if limit > 0 else tags


def _release_line(artist: str, name: str, kind: str, suffix: str) -> str:
    """«Artist — Name (Album) | Без цензуры». Пустая часть выпадает со своим разделителем."""
    title = " — ".join(part for part in (artist.strip(), name.strip()) if part)
    if not title:
        return ""
    if kind.strip():
        title = f"{title} ({kind.strip()})"
    return f"{title} | {suffix.strip()}" if suffix.strip() else title


def build_tracklist(titles: list[str], durations_s: list[int]) -> str:
    """Треклист с тайм-кодами: каждая строка «MM:SS N. Название»."""
    lines = []
    offset = 0
    for index, title in enumerate(titles, start=1):
        lines.append(f"{_format_timecode(offset)} {index}. {title}")
        offset += durations_s[index - 1]
    return "\n".join(lines)


def _format_timecode(seconds: int) -> str:
    hours, remainder = divmod(seconds, 3600)
    minutes, secs = divmod(remainder, 60)
    if hours:
        return f"{hours}:{minutes:02d}:{secs:02d}"
    return f"{minutes:02d}:{secs:02d}"


def clean_description(description: str) -> str:
    """Убирает служебное авто-описание YouTube. Обычное описание оставляет как есть."""
    text = description.strip()
    if any(marker in text for marker in _YT_AUTOGEN_MARKERS):
        return ""
    return text


def build_post_text(title: str, description: str, ad_block: str) -> str:
    """Собирает текст поста YouTube-потока: заголовок, описание, рекламный блок.

    Порядок по ТЗ: оригинальное название -> оригинальное описание -> реклама.
    """
    parts = [p for p in (title.strip(), description.strip(), ad_block.strip()) if p]
    text = "\n\n".join(parts)
    if len(text) <= VK_MESSAGE_LIMIT:
        return text

    # Ужимаем описание, сохраняя заголовок и рекламу целиком.
    reserved = len(title.strip()) + len(ad_block.strip()) + len("\n\n") * 2
    room = VK_MESSAGE_LIMIT - reserved
    trimmed = description.strip()[: max(0, room)].rstrip()
    parts = [p for p in (title.strip(), trimmed, ad_block.strip()) if p]
    return "\n\n".join(parts)
